2021-09-22 10:33:54,473 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 10:34:58,741 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 10:36:33,152 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 10:43:42,161 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 10:46:41,837 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 10:47:35,879 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 10:50:56,737 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 15:43:06,961 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 15:44:35,616 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 15:47:54,405 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 15:48:44,725 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 17:31:59,210 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 17:32:20,351 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 17:32:43,749 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-22 17:35:53,116 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-23 08:40:06,222 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-23 08:40:27,804 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 08:40:42,845 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 08:43:18,004 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 08:55:43,381 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-23 08:56:00,616 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 08:56:14,701 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 08:57:49,500 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 08:58:35,721 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 09:07:30,531 INFO: Microblog startup [in d:\py\vd\app\__init__.py:57]
2021-09-23 09:07:41,223 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 09:07:42,954 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 09:07:48,523 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
2021-09-23 09:07:50,019 ERROR: Exception on /background_process_test [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'background_process_test' did not return a valid response. The function either returned None or ended without a return statement.
