2021-10-13 17:57:03,590 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 17:57:49,914 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 17:59:07,777 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 17:59:17,370 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 18:00:36,232 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 18:03:35,281 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 18:03:44,525 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 18:09:33,638 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-14 09:33:49,036 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-14 10:17:57,213 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-14 10:17:59,178 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-14 10:18:14,258 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-14 10:18:55,270 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-14 10:18:57,468 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'd:\\py\x0bD\x07pp\\static'
2021-10-14 10:24:39,663 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-14 10:24:43,738 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'd:\\py\x0bD\x07pp\\static'
2021-10-14 10:24:51,284 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'd:\\py\x0bD\x07pp\\static'
2021-10-14 10:25:11,225 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
