2021-10-13 10:33:22,375 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 10:33:23,229 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 10:35:23,222 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 10:36:19,561 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 10:36:22,502 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: '\\static'
2021-10-13 10:36:59,633 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 10:37:00,736 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 10:37:25,883 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 10:38:24,589 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 10:38:26,269 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'D:\\py\x0bD\x07pp\\static'
2021-10-13 10:48:29,179 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'D:\\py\x0bD\x07pp\\static'
2021-10-13 17:37:53,773 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 17:38:03,935 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'D:\\py\x0bD\x07pp\\static'
2021-10-13 17:49:45,625 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-10-13 17:56:48,501 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
2021-10-13 17:56:52,503 ERROR: Exception on /upload [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\vD\app\routes.py", line 236, in uploaddd
    files = os.listdir(app.config['UPLOAD_PATH'])
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'static'
